export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';


