export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';

export const CREATE_BRAND = 'CREATE_BRAND';

export const FETCH_ALL_CARS = 'FETCH_ALL_CARS';
export const FETCH_ALL_CARS_SUCCESS = 'FETCH_ALL_CARS_SUCCESS';
export const FETCH_CAR = 'FETCH_CAR';
export const FETCH_CAR_SUCCESS = 'FETCH_CAR_SUCCESS';
export const CREATE_CAR = 'CREATE_CAR';
export const UPDATE_CAR = 'UPDATE_CAR';
export const DELETE_CAR = 'DELETE_CAR';


